<x-app-layout title="Queue & Logs" active="queue">
    <x-slot:breadcrumb>Queue &amp; Logs / Execution Jobs</x-slot:breadcrumb>
    <x-slot:subtitle>Execution jobs generated by automation flows. Retry failed jobs from here.</x-slot:subtitle>

    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
        <x-stat-card label="Pending" :value="$counts['pending'] ?? 0" meta="Awaiting worker" />
        <x-stat-card label="Processing" :value="$counts['processing'] ?? 0" meta="In flight" />
        <x-stat-card label="Completed" :value="$counts['completed'] ?? 0" meta="Succeeded" />
        <x-stat-card label="Failed" :value="$counts['failed'] ?? 0" meta="Need attention" />
        <x-stat-card label="Retried" :value="$retried" meta="Attempts > 1" />
    </section>

    <div class="flex flex-wrap gap-2">
        @php $all = ['' => 'All', 'pending' => 'Pending', 'processing' => 'Processing', 'completed' => 'Completed', 'failed' => 'Failed', 'held' => 'Held']; @endphp
        @foreach ($all as $key => $label)
            <a href="{{ route('admin.queue.index', array_filter(['status' => $key])) }}"
               class="rounded-xl border px-3 py-1.5 text-sm font-bold {{ (string) $status === (string) $key ? 'border-blue text-blue' : 'border-border text-muted' }}">
                {{ $label }}@isset($counts[$key]) <span class="opacity-70">({{ $counts[$key] }})</span>@endisset
            </a>
        @endforeach
    </div>

    <x-card :padded="false">
        <div class="overflow-x-auto">
            <table class="w-full text-sm">
                <thead>
                    <tr class="text-left text-xs uppercase tracking-wide text-muted" style="background: var(--table-head);">
                        <th class="px-4 py-3 font-extrabold">#</th>
                        <th class="px-4 py-3 font-extrabold">Flow</th>
                        <th class="px-4 py-3 font-extrabold">Action</th>
                        <th class="px-4 py-3 font-extrabold">Attempts</th>
                        <th class="px-4 py-3 font-extrabold">Status</th>
                        <th class="px-4 py-3 font-extrabold">Finished</th>
                        <th class="px-4 py-3 font-extrabold text-right">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($jobs as $job)
                        <tr class="border-t border-border">
                            <td class="px-4 py-3 text-muted">{{ $job->id }}</td>
                            <td class="px-4 py-3">{{ $job->flow?->name ?? '—' }}</td>
                            <td class="px-4 py-3"><code class="text-xs">{{ $job->type }}</code></td>
                            <td class="px-4 py-3 text-muted">{{ $job->attempts }}</td>
                            <td class="px-4 py-3"><x-badge :color="$job->statusColor()">{{ ucfirst($job->status) }}</x-badge></td>
                            <td class="px-4 py-3 text-muted text-xs whitespace-nowrap"><x-datetime :value="$job->finished_at" format="H:i:s" :tz="false" /></td>
                            <td class="px-4 py-3">
                                <div class="flex items-center justify-end gap-2">
                                    <a href="{{ route('admin.queue.show', $job) }}" class="rounded-lg border border-border bg-panel px-3 py-1.5 font-bold">Inspect</a>
                                    @can('queue.retry')
                                        @if (in_array($job->status, ['failed', 'held'], true))
                                            <form method="POST" action="{{ route('admin.queue.retry', $job) }}">
                                                @csrf
                                                <button class="rounded-lg border border-border bg-panel px-3 py-1.5 font-bold">Retry</button>
                                            </form>
                                        @endif
                                    @endcan
                                </div>
                            </td>
                        </tr>
                    @empty
                        <tr><td colspan="7" class="px-4 py-8 text-center text-muted">No execution jobs yet.</td></tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </x-card>

    {{ $jobs->links() }}
</x-app-layout>
